nats:
    enabled: false

spring:
    docker:
        compose:
            enabled: ${SPRING_DOCKER_COMPOSE_ENABLED:true}

monitoring:
    run-on-startup: false

github:
    app:
        id: 0
        privateKey: ""
        privateKeyLocation: ""
    auth-token: ""

hephaestus:
    workspace:
        init-default: false
