nats:
    enabled: false

spring:
    docker:
        compose:
            enabled: false
            lifecycle-management: none
            skip:
                in-tests: true
    liquibase:
        enabled: false
    datasource:
        url: jdbc:h2:mem:hephaestus-specs;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_LOWER=TRUE
        username: sa
        password: ""
        driver-class-name: org.h2.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect

monitoring:
    run-on-startup: false

github:
    app:
        id: 0
        privateKey: ""
        privateKeyLocation: ""
    auth-token: ""

hephaestus:
    workspace:
        init-default: false
